### PR TITLE
14 rework random wave generation

### LINKED ISSUE #14: Rework random wave generation
-Replace old wave generation with new wave generation

### PR DESCRIPTION
**Pull request by sancheky22**

### CODE REVIEW

**Comment by Cesium1289** [comment]
I think you can remove the "GenerateRandomWave", "WaveFunc", and TestAddMethod functions in the WaveParameters. I don't believe it is called anywhere in the code.

**Comment by tieph2** [comment]
I think there's already an implementation of the GenerateRandomWaveType on line 315 of WaveParameters.cpp, which is on line 113 of WaveGenerator.cpp.

**Comment by tieph2** [comment]
setScaleType should be removed, since we no longer are going to implement the scale feature.

**Review by tieph2 — APPROVED** [review]
Code looks good.

**Pull request merged**
